### ISSUE TITLE
Method 1 error

### ISSUE THREAD

**Issue by Sky640q** [t0neex/ActiveDirectory-Intune-Defender-Forcepoint-UCMDB-Reporting-wPowerBI#1]
Hello, Using method 1, i cannot just use an app registration information, it will ask for Odata feed as well.

**Comment by samet-ibis** [comment]
Hi,

OData feed must be your Intune Data Warehouse URL. But if it’s not can you
please send me a screenshot? I’ll return you like 8-9 hours later now it’s
1am here 😅

Thanks,
Best Regards.

**Comment by samet-ibis** [comment]
Hi,

Is there any problem with getting data? I can help you in 5 hours with Zoom
also. Or you can just send me screenshots :)

Thanks.

t0neex ***@***.***>, 19 Tem 2023 Çar, 00:59 tarihinde şunu yazdı:

> Hi,
>
> OData feed must be your Intune Data Warehouse URL. But if it’s not can you
> please send me a screenshot? I’ll return you like 8-9 hours later now it’s
> 1am here 😅
>
> Thanks,
> Best Regards.
>
